spring:
  cloud:
    stream:
      bindings:
        metricsChannel:
          destination: metrics
        input:
          destination: metrics
          group: metrics-group
          consumer:
            durableSubscription: true